azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 10GiB
github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
build_platform:
  linux_aarch64: linux_64
